name: vprofile actions
on: push
env:
    AWS_REGION: eu-west-3
    ECR_REPOSITORY: github-actions-vprofile
    EKS_CLUSTER: vprofile-eks

jobs:
    Testing:
        runs-on: ubuntu-latest
        steps: 
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Maven Test
              run: mvn test

            - name: Checkstyle
              run: mvn checkstyle:checkstyle


            - name: Set java version
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '11'

            - name: setup sonarqube
              uses: warchant/setup-sonar-scanner@v7
            
            - name: SonarQube Scan
              run: sonar-scanner
                -Dsonar.host.url=${{ secrets.SONAR_URL }}
                -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
                -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
                -Dsonar.sources=src/
                -Dsonar.java.binaries=target/test-classes/com/visualpathit/account
                -Dsonar.junit.reportPaths=target/surefire-reports/
                -Dsonar.jacoco.reportPaths=target/jacoco.exec
                -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

            - name: Sonarqube quality gate
              id: sonarqube
              uses: sonarsource/sonarqube-quality-gate-action@master
              timeout-minutes: 5
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST: ${{ secrets.SONAR_URL }}
                SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

    Build_and_publish:
        runs-on: ubuntu-latest
        needs: Testing
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Build and upload image to ECR
              uses: vitr/actions-build-and-upload-to-ecs@master
              with:
                access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                region: ${{ env.AWS_REGION }}
                account_id: ${{ secrets.AWS_ACCOUNT_ID }}
                repo: ${{ env.ECR_REPOSITORY }}
                tag: latest,${{ github.run_number }}
                daemon_off: false
                dockerfile: ./Dockerfile
                context: ./
    
    Deploy:
      needs: Build_and_publish
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to EKS
          uses: actions/checkout@v4
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
  
        - name: Get Kubeconfig
          run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
        - name: Login to Amazon ECR
          run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        
        - name: Deploy Helm
          uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
            cluster-name: ${{ env.EKS_CLUSTER }}
            # config-files: .github/values/dev.yaml
            chart-path: helm/vprofilecharts
            namespace: default
            values: appimage=${{ secrets.REGISTRY}}/${{ env.ECR_REPOSITORY }}:latest
            name: vprofile-stack